SELECT
    ALIAS_0.ID ALIAS_0_ID,
    ALIAS_0.ESTADO ALIAS_0_ESTADO,
    ALIAS_0.NOMBREDESTINATARIO ALIAS_0_NOMBREDESTINATARIO,
    ALIAS_1.NOMBRE ALIAS_1_NOMBRE
FROM
    V_TRFACTURAVENTA ALIAS_0
    INNER JOIN V_CLIENTE ALIAS_2 ON ALIAS_0.DESTINATARIO_ID = ALIAS_2.ID
    INNER JOIN V_PERSONA ALIAS_1 ON ALIAS_2.ENTEASOCIADO_ID = ALIAS_1.ID
WHERE
    ALIAS_0.ESTADO = 'C'