    aView.AddJoin(NewJoinSpec(aView.ColumnFromPath("ID"), NewColumnSpec("CENTROCOSTOS", "id", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_CENTROCOSTOS", "ID", ""), NewColumnSpec("CENTROCOSTOS", "BOEXTENSION", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_CENTROCOSTOS", "PLAZOENTREGA", ""), NewColumnSpec("UD_PLAZOENTREGA", "BO_PLACE_ID", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("PERSLIST", "ID", ""), NewColumnSpec("BOLIST", "BO_ITEMS", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("BOLIST", "ID", ""), NewColumnSpec("UD_PLAZOENTREGA", "PROVEEDOR", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_PLAZOENTREGA", "PROVEEDOR", ""), NewColumnSpec("PROVEEDOR", "ID", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "ENTEASOCIADO", ""), NewColumnSpec("PERSONA", "ID", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "LISTAPRECIO", ""), NewColumnSpec("LISTAPRECIO", "ID", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("LISTAPRECIO", "PRECIOS", ""), NewColumnSpec("PRECIO", "BO_PLACE", ""), false))
	aView.AddJoin(NewJoinSpec(aView.ColumnFromPath("ID"), NewColumnSpec("PRECIO", "REFERENCIA", ""), false))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PROVEEDOR", "ACTIVESTATUS", ""), " = ", 0))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "DESDEFECHA", ""), " <= ", Now))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "HASTAFECHA", ""), " >= ", Now))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("CENTROCOSTOS", "ID", ""), " = ", xTr.CentroCostos.ID))
	
	'aView.AddJoin(NewJoinSpec(aView.ColumnFromPath("ID"), NewColumnSpec("PRECIO", "REFERENCIA", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("PRECIO", "BO_PLACE", ""), NewColumnSpec("LISTAPRECIO", "PRECIOS", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("LISTAPRECIO", "ID", ""), NewColumnSpec("PROVEEDOR", "LISTAPRECIO", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "ENTEASOCIADO", ""), NewColumnSpec("PERSONA", "ID", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "ID", ""), NewColumnSpec("PERSLIST", "ITEM", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("PERSLIST", "ID", ""), NewColumnSpec("BOLIST", "BO_ITEMS", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("BOLIST", "ID", ""), NewColumnSpec("UD_CENTROCOSTOS", "PROVEEDORSERVICIO", ""), false))
	'aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_CENTROCOSTOS", "ID", ""), NewColumnSpec("CENTROCOSTOS", "BOEXTENSION", ""), false))
	'aView.AddFilter(NewFilterSpec(NewColumnSpec("PROVEEDOR", "ACTIVESTATUS", ""), " = ", 0))
	'aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "DESDEFECHA", ""), " <= ", Now))
	'aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "HASTAFECHA", ""), " >= ", Now))
	'aView.AddFilter(NewFilterSpec(NewColumnSpec("CENTROCOSTOS", "ID", ""), " = ", xTr.CentroCostos.ID))




	aView.AddJoin(NewJoinSpec(aView.ColumnFromPath("ID"), NewColumnSpec("PRECIO", "REFERENCIA", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("PRECIO", "BO_PLACE", ""), NewColumnSpec("LISTAPRECIO", "PRECIOS", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("LISTAPRECIO", "ID", ""), NewColumnSpec("PROVEEDOR", "LISTAPRECIO", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "ENTEASOCIADO", ""), NewColumnSpec("PERSONA", "ID", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("PROVEEDOR", "ID", ""), NewColumnSpec("UD_PLAZOENTREGA", "PROVEEDOR", ""), false))

	aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_PLAZOENTREGA", "BO_PLACE_ID", ""), NewColumnSpec("UD_CENTROCOSTOS", "PLAZOSENTREGA", ""), false))
	aView.AddJoin(NewJoinSpec(NewColumnSpec("UD_CENTROCOSTOS", "ID", ""), NewColumnSpec("CENTROCOSTOS", "BOEXTENSION", ""), false))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PROVEEDOR", "ACTIVESTATUS", ""), " = ", 0))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "DESDEFECHA", ""), " <= ", Now))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("PRECIO", "HASTAFECHA", ""), " >= ", Now))
	aView.AddFilter(NewFilterSpec(NewColumnSpec("CENTROCOSTOS", "ID", ""), " = ", xTr.CentroCostos.ID))