USE [ISCOT]
GO

/****** Object:  StoredProcedure [dbo].[SP_Cliente_ACobrar2]    Script Date: 23/05/2024 18:52:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		José Luis Fantasia
-- Create date: 10/01/2017
-- Description:	Saldos a Cobrar de Clientes Online
-- =============================================

--Se agrego el filtro por estado judicial - 23/05/2024 Rfierro
ALTER PROCEDURE [dbo].[SP_Cliente_ACobrar2]
	
AS
BEGIN
	SELECT Cliente
	--,SUM(CASE WHEN Dias <= 15 THEN Vencido ELSE 0.0 END) AS Menos_15
	,SUM(CASE WHEN Dias >= 0 AND Dias <= 30 THEN Vencido ELSE 0.0 END) AS Menos_30
	,SUM(CASE WHEN Dias > 30 AND Dias <= 60 THEN Vencido ELSE 0.0 END) AS Menos_60
	,SUM(CASE WHEN Dias > 60 THEN Vencido ELSE 0.0 END) AS Mas_60
	FROM (



		SELECT per.NOMBRE AS Cliente
		,ABS(DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103)))) AS Dias
		,cp.DESCRIPCION AS Comprobante
		,(CASE WHEN DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0 THEN cp.SALDO2_IMPORTE ELSE 0.0 END) 
			* (CASE WHEN cp.TIPOTRANSACCION_ID = '{DD86C466-25ED-4F2E-A1EF-4A7E454F685B}' THEN -1 ELSE 1 END) AS Vencido
		FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
		INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
		INNER JOIN V_PERSONA AS per WITH(NOLOCK) ON cli.ENTEASOCIADO_ID = per.ID
		INNER JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
		INNER JOIN UD_TIPOPAGO AS ud_tp WITH(NOLOCK) ON tp.BOEXTENSION_ID = ud_tp.ID
		WHERE cp.BO_PLACE_ID IS NOT NULL
		AND cp.SALDADO = 'F'
		AND cp.NIVEL = 1
		AND cp.CPCOMPRAS = 'F'
		AND DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0
		AND cp.TIPOTRANSACCION_ID = '{DD86C466-25ED-4F2E-A1EF-4A7E454F685B}'	--NCV


		union all


		SELECT per.NOMBRE AS Cliente
		,ABS(DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103)))) AS Dias
		,cp.DESCRIPCION AS Comprobante
		,(CASE WHEN DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0 THEN cp.SALDO2_IMPORTE ELSE 0.0 END) 
			* (CASE WHEN cp.TIPOTRANSACCION_ID = '{DD86C466-25ED-4F2E-A1EF-4A7E454F685B}' THEN -1 ELSE 1 END) AS Vencido
		FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
		INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
		INNER JOIN V_PERSONA AS per WITH(NOLOCK) ON cli.ENTEASOCIADO_ID = per.ID
		INNER JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
		INNER JOIN UD_TIPOPAGO AS ud_tp WITH(NOLOCK) ON tp.BOEXTENSION_ID = ud_tp.ID
		inner join TRFACTURAVENTA as trv on cp.id = trv.COMPROMISOPAGO_ID
		inner join UD_FACTURAVENTA as UDfv on trv.BOEXTENSION_ID = UDfv.id
		WHERE cp.BO_PLACE_ID IS NOT NULL
		AND cp.SALDADO = 'F'
		AND cp.NIVEL = 1
		AND cp.CPCOMPRAS = 'F'
		--AND cp.SUMA = 'T'
		AND DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0
		AND cp.TIPOTRANSACCION_ID = '{51DFC3EB-13BB-4CF4-82A6-2CA7CEEE524A}' -- FAV
		and ISNULL((SELECT TOP 1 oef.ESTADOPAGO_ID AS OBS FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = UDfv.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '{00000000-0000-0000-0000-000000000000}') <> '{6CA42AF2-C52A-4B1F-A7AE-71999839B861}'--Filtra las fv con estado de pago distinto a judicial


		union all


		SELECT per.NOMBRE AS Cliente
		,ABS(DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103)))) AS Dias
		,cp.DESCRIPCION AS Comprobante
		,(CASE WHEN DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0 THEN cp.SALDO2_IMPORTE ELSE 0.0 END) 
			* (CASE WHEN cp.TIPOTRANSACCION_ID = '{DD86C466-25ED-4F2E-A1EF-4A7E454F685B}' THEN -1 ELSE 1 END) AS Vencido
		FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
		INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
		INNER JOIN V_PERSONA AS per WITH(NOLOCK) ON cli.ENTEASOCIADO_ID = per.ID
		INNER JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
		INNER JOIN UD_TIPOPAGO AS ud_tp WITH(NOLOCK) ON tp.BOEXTENSION_ID = ud_tp.ID
		inner join TRFACTURAVENTA as trv on cp.id = trv.COMPROMISOPAGO_ID
		inner join UD_FACTURAVENTA as UDfv on trv.BOEXTENSION_ID = UDfv.id
		WHERE cp.BO_PLACE_ID IS NOT NULL
		AND cp.SALDADO = 'F'
		AND cp.NIVEL = 1
		AND cp.CPCOMPRAS = 'F'
		AND DATEDIFF(DD, GETDATE(), DATEADD(DD, ud_tp.DIAS, CONVERT(date, LEFT(cp.FECHAEMISION, 8), 103))) < 0
		AND cp.TIPOTRANSACCION_ID = '{C2FB7B1F-4C1A-473E-A47D-DA4F335FD08B}' --NDV
		and ISNULL((SELECT TOP 1 oef.ESTADOPAGO_ID AS OBS FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = UDfv.ESTADOFACTURA_ID
		ORDER BY oef.FECHA DESC), '{00000000-0000-0000-0000-000000000000}') <> '{6CA42AF2-C52A-4B1F-A7AE-71999839B861}'--Filtra las fv con estado de pago distinto a judicial


	) Q
	GROUP BY Cliente
	ORDER BY Cliente
END

GO


