USE [ISCOT]
GO

/****** Object:  StoredProcedure [dbo].[SP_Cliente_ACobrar_Vencidas]    Script Date: 25/03/2024 07:43:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--USE [ISCOT]
--GO



---- =============================================
---- Author:		Rodrigo Fierro
---- Create date: 25/03/2024
---- =============================================
ALTER PROCEDURE [dbo].[SP_Cliente_ACobrar_Vencidas]
	@FECHA_DESDE			varchar(8),

	@FECHA_HASTA			varchar(8)

	@CLIENTE	            varchar(50)
AS
BEGIN
	-- FACTURAS.
		WITH CTE AS (
	SELECT cli.DENOMINACION AS Cliente
	,fv.NOMBRE AS Comprobante, 
	cp.SALDO2_IMPORTE * (CASE WHEN cp.TIPO IN ('CPCREDITO', 'CPRECIBO') THEN -1 ELSE 1 END) AS Saldo
	,(CASE WHEN DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8)))
	, GETDATE()) > 0 THEN 'VENCIDA' ELSE '' END) AS Vencida
	,tsfv.NOMBRE AS Tipo
	,(CASE SUBSTRING(udfv.FECHASERVICIO, 5, 2)
		WHEN '01' THEN 'ENERO'
		WHEN '02' THEN 'FEBRERO'
		WHEN '03' THEN 'MARZO'
		WHEN '04' THEN 'ABRIL'
		WHEN '05' THEN 'MAYO'
		WHEN '06' THEN 'JUNIO'
		WHEN '07' THEN 'JULIO'
		WHEN '08' THEN 'AGOSTO'
		WHEN '09' THEN 'SEPTIEMBRE'
		WHEN '10' THEN 'OCTUBRE'
		WHEN '11' THEN 'NOVIEMBRE'
		WHEN '12' THEN 'DICIEMBRE' 
		ELSE '' END) + '-' + LEFT(udfv.FECHASERVICIO, 4) AS Servicio
	,DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8))), GETDATE()) AS DiasHoy
	,ISNULL(cc.NOMBRE, ' ** Sin Centro ** ') AS CentroCostos
	,ISNULL((SELECT TOP 1 ep.CODIGO AS CodEP FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		LEFT JOIN ITEMTIPOCLASIFICADOR AS ep WITH(NOLOCK) ON oef.ESTADOPAGO_ID = ep.ID
		WHERE oef.BO_PLACE_ID = udfv.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '00') AS EstadoPago
	,ISNULL(udfv.SEGUIMIENTO, '') AS Seguimiento
	,CONVERT(date, udfv.FECHASERVICIO, 103) AS FECHASERVICIO
	,ISNULL((SELECT TOP 1 CONVERT(date, oef.FECHA, 103) AS FECHA FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udfv.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), CONVERT(date, '01/01/2000', 103)) AS FECHAESTADO
	,ISNULL((SELECT TOP 1 oef.OBSERVACION AS OBS FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udfv.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '') AS OBSERVAESTADO
	FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
	INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
	LEFT JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
	LEFT JOIN UD_TIPOPAGO AS udtp WITH(NOLOCK) ON tp.BOEXTENSION_ID = udtp.ID
	INNER JOIN TRFACTURAVENTA AS fv WITH(NOLOCK) ON fv.ID = cp.TRORIGINANTE_ID
	INNER JOIN UD_FACTURAVENTA AS udfv WITH(NOLOCK) ON udfv.ID = fv.BOEXTENSION_ID
	INNER JOIN ITEMTIPOCLASIFICADOR AS tsfv WITH(NOLOCK) ON tsfv.ID = udfv.TIPOSERVICIO_ID
	LEFT JOIN CENTROCOSTOS AS cc WITH(NOLOCK) ON cp.CENTROCOSTOS_ID = cc.ID
	left JOIN UD_ESTADOFACTURACION AS ef WITH(NOLOCK) ON udfv.ESTADOFACTURA_ID = ef.BO_PLACE_ID
	LEFT JOIN ITEMTIPOCLASIFICADOR AS ep WITH(NOLOCK) ON ef.ESTADOPAGO_ID = ep.ID
	WHERE cp.BO_PLACE_ID IS NOT NULL
	AND cp.SALDADO = 'F'
	AND cp.NIVEL = 1
	AND cp.CPCOMPRAS = 'F'
	AND fv.ESTADO = 'C'
	AND LEFT(cp.FECHAEMISION, 8) BETWEEN @FECHA_DESDE AND @FECHA_HASTA
	AND ROUND(cp.SALDO2_IMPORTE, 2) > 0.03

	UNION ALL

	-- DEBITOS.
	SELECT cli.DENOMINACION AS Cliente
	,nd.NOMBRE AS Comprobante
	,cp.SALDO2_IMPORTE * (CASE WHEN cp.TIPO IN ('CPCREDITO', 'CPRECIBO') THEN -1 ELSE 1 END) AS Saldo
	,(CASE WHEN DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8))), GETDATE()) > 0 THEN 'VENCIDA' ELSE '' END) AS Vencida
	,tsnd.NOMBRE AS Tipo
	,(CASE SUBSTRING(udnd.FECHASERVICIO, 5, 2)
		WHEN '01' THEN 'ENERO'
		WHEN '02' THEN 'FEBRERO'
		WHEN '03' THEN 'MARZO'
		WHEN '04' THEN 'ABRIL'
		WHEN '05' THEN 'MAYO'
		WHEN '06' THEN 'JUNIO'
		WHEN '07' THEN 'JULIO'
		WHEN '08' THEN 'AGOSTO'
		WHEN '09' THEN 'SEPTIEMBRE'
		WHEN '10' THEN 'OCTUBRE'
		WHEN '11' THEN 'NOVIEMBRE'
		WHEN '12' THEN 'DICIEMBRE' 
		ELSE '' END) + '-' + LEFT(udnd.FECHASERVICIO, 4) AS Servicio
	,DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8))), GETDATE()) AS DiasHoy
	,ISNULL(cc.NOMBRE, ' ** Sin Centro ** ') AS CentroCostos
	,ISNULL((SELECT TOP 1 ep.CODIGO AS CodEP FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		LEFT JOIN ITEMTIPOCLASIFICADOR AS ep WITH(NOLOCK) ON oef.ESTADOPAGO_ID = ep.ID
		WHERE oef.BO_PLACE_ID = udnd.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '00') AS EstadoPago
	,ISNULL(udnd.SEGUIMIENTO, '') AS Seguimiento
	,CONVERT(date, udnd.FECHASERVICIO, 103) AS FECHASERVICIO
	,ISNULL((SELECT TOP 1 CONVERT(date, oef.FECHA, 103) AS FECHA FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udnd.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), CONVERT(date, '01/01/2000', 103)) AS FECHAESTADO
	,ISNULL((SELECT TOP 1 oef.OBSERVACION AS OBS FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udnd.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '') AS OBSERVAESTADO
	FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
	INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
	LEFT JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
	LEFT JOIN UD_TIPOPAGO AS udtp WITH(NOLOCK) ON tp.BOEXTENSION_ID = udtp.ID
	INNER JOIN TRDEBITOVENTA AS nd WITH(NOLOCK) ON nd.ID = cp.TRORIGINANTE_ID
	INNER JOIN UD_DEBITOVENTA AS udnd WITH(NOLOCK) ON udnd.ID = nd.BOEXTENSION_ID
	INNER JOIN ITEMTIPOCLASIFICADOR AS tsnd WITH(NOLOCK) ON tsnd.ID = udnd.TIPOSERVICIO_ID
	LEFT JOIN CENTROCOSTOS AS cc WITH(NOLOCK) ON cp.CENTROCOSTOS_ID = cc.ID
	left JOIN UD_ESTADOFACTURACION AS ef WITH(NOLOCK) ON udnd.ESTADOFACTURA_ID = ef.BO_PLACE_ID
	LEFT JOIN ITEMTIPOCLASIFICADOR AS epd WITH(NOLOCK) ON ef.ESTADOPAGO_ID = epd.ID
	WHERE cp.BO_PLACE_ID IS NOT NULL
	AND cp.SALDADO = 'F'
	AND cp.NIVEL = 1
	AND cp.CPCOMPRAS = 'F'
	AND nd.ESTADO = 'C'
	AND LEFT(cp.FECHAEMISION, 8) BETWEEN @FECHA_DESDE AND @FECHA_HASTA
	AND ROUND(cp.SALDO2_IMPORTE, 2) > 0.03

	UNION ALL

	-- CREDITOS.
	SELECT cli.DENOMINACION AS Cliente
	,nc.NOMBRE AS Comprobante
	,cp.SALDO2_IMPORTE * (CASE WHEN cp.TIPO IN ('CPCREDITO', 'CPRECIBO') THEN -1 ELSE 1 END) AS Saldo
	,(CASE WHEN DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8))), GETDATE()) > 0 THEN 'VENCIDA' ELSE '' END) AS Vencida
	,tsnc.NOMBRE AS Tipo
	,(CASE SUBSTRING(udnc.FECHASERVICIO, 5, 2)
		WHEN '01' THEN 'ENERO'
		WHEN '02' THEN 'FEBRERO'
		WHEN '03' THEN 'MARZO'
		WHEN '04' THEN 'ABRIL'
		WHEN '05' THEN 'MAYO'
		WHEN '06' THEN 'JUNIO'
		WHEN '07' THEN 'JULIO'
		WHEN '08' THEN 'AGOSTO'
		WHEN '09' THEN 'SEPTIEMBRE'
		WHEN '10' THEN 'OCTUBRE'
		WHEN '11' THEN 'NOVIEMBRE'
		WHEN '12' THEN 'DICIEMBRE' 
		ELSE '' END) + '-' + LEFT(udnc.FECHASERVICIO, 4) AS Servicio
	,DATEDIFF(DD, DATEADD(DD, ISNULL(udtp.DIAS, 0),CONVERT(date, LEFT(cp.FECHAEMISION, 8))), GETDATE()) AS DiasHoy
	,ISNULL(cc.NOMBRE, ' ** Sin Centro ** ') AS CentroCostos
	,ISNULL((SELECT TOP 1 ep.CODIGO AS CodEP FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		LEFT JOIN ITEMTIPOCLASIFICADOR AS ep WITH(NOLOCK) ON oef.ESTADOPAGO_ID = ep.ID
		WHERE oef.BO_PLACE_ID = udnc.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '00') AS EstadoPago
	,ISNULL(udnc.SEGUIMIENTO, '') AS Seguimiento
	,CONVERT(date, udnc.FECHASERVICIO, 103) AS FECHASERVICIO
	,ISNULL((SELECT TOP 1 CONVERT(date, oef.FECHA, 103) AS FECHA FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udnc.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), CONVERT(date, '01/01/2000', 103)) AS FECHAESTADO
	,ISNULL((SELECT TOP 1 oef.OBSERVACION AS OBS FROM UD_ESTADOFACTURACION AS oef WITH(NOLOCK) 
		WHERE oef.BO_PLACE_ID = udnc.ESTADOFACTURA_ID 
		ORDER BY oef.FECHA DESC), '') AS OBSERVAESTADO
	FROM V_COMPROMISOPAGO AS cp WITH(NOLOCK)
	INNER JOIN CLIENTE AS cli WITH(NOLOCK) ON cli.ID = cp.OPERADORCOMERCIAL_ID
	LEFT JOIN TIPOPAGO AS tp WITH(NOLOCK) ON cli.TIPOPAGO_ID = tp.ID
	LEFT JOIN UD_TIPOPAGO AS udtp WITH(NOLOCK) ON tp.BOEXTENSION_ID = udtp.ID
	INNER JOIN TRCREDITOVENTA AS nc WITH(NOLOCK) ON nc.ID = cp.TRORIGINANTE_ID
	INNER JOIN UD_CREDITOVENTA AS udnc WITH(NOLOCK) ON udnc.ID = nc.BOEXTENSION_ID
	INNER JOIN ITEMTIPOCLASIFICADOR AS tsnc WITH(NOLOCK) ON tsnc.ID = udnc.TIPOSERVICIO_ID
	LEFT JOIN CENTROCOSTOS AS cc WITH(NOLOCK) ON cp.CENTROCOSTOS_ID = cc.ID
	left JOIN UD_ESTADOFACTURACION AS ef WITH(NOLOCK) ON udnc.ESTADOFACTURA_ID = ef.BO_PLACE_ID
	LEFT JOIN ITEMTIPOCLASIFICADOR AS epc WITH(NOLOCK) ON ef.ESTADOPAGO_ID = epc.ID
	WHERE cp.BO_PLACE_ID IS NOT NULL
	AND cp.SALDADO = 'F'
	AND cp.NIVEL = 1
	AND cp.CPCOMPRAS = 'F'
	AND nc.ESTADO = 'C'
	AND LEFT(cp.FECHAEMISION, 8) BETWEEN @FECHA_DESDE AND @FECHA_HASTA
	AND ROUND(cp.SALDO2_IMPORTE, 2) > 0.03
	--      agregue esto nada mas ORDER BY [FECHASERVICIO],
	--ORDER BY [FECHASERVICIO], [Cliente], [Comprobante]
	)
	-- Calcular los saldos no vencidos y vencidos
	SELECT
    Cliente,
    Comprobante,
    Saldo,
    Vencida,
    Tipo,
    Servicio,
    DiasHoy,
    isnull(CentroCostos,'') as 'CentroCostos',
    EstadoPago,
    Seguimiento,
    FECHASERVICIO,
    FECHAESTADO,
    OBSERVAESTADO,
    SUM(CASE WHEN Vencida = '' THEN CASE WHEN EstadoPago = '04' THEN 0 ELSE Saldo END ELSE 0 END) AS NoVencido,
    SUM(CASE WHEN Vencida = 'VENCIDA' THEN CASE WHEN EstadoPago = '04' THEN 0 ELSE Saldo END ELSE 0 END) AS Vencido
FROM CTE
WHERE Comprobante NOT LIKE '%ANU%'
and Vencida = 'VENCIDA'
and Cliente = @CLIENTE
GROUP BY
    Cliente,
    Comprobante,
    Saldo,
    Vencida,
    Tipo,
    Servicio,
    DiasHoy,
    CentroCostos,
    EstadoPago,
    Seguimiento,
    FECHASERVICIO,
    FECHAESTADO,
    OBSERVAESTADO
ORDER BY Cliente, Comprobante --, FECHASERVICIO;
END




GO

