SELECT uitem.PRODUCTO_ID 
				,tipo.NOMBRE 
				,prod.DESCRIPCION 
				,SUM(uitem.CANTIDAD) AS CANTIDAD, uitem.OBSERVACIONES 
				FROM TRSOLICITUD AS pip WITH(NOLOCK) 
				INNER JOIN UD_PIPRH AS upip WITH(NOLOCK) ON pip.BOEXTENSION_ID = upip.ID 
				INNER JOIN UD_EMPLEADOPIPRH AS uitem WITH(NOLOCK) ON upip.ITEMS_ID = uitem.BO_PLACE_ID 
				INNER JOIN PRODUCTO AS prod WITH(NOLOCK) ON uitem.PRODUCTO_ID = prod.ID 
				INNER JOIN UD_PRODUCTO AS uprod WITH(NOLOCK) ON prod.BOEXTENSION_ID = uprod.ID 
				INNER JOIN ITEMTIPOCLASIFICADOR AS tipo WITH(NOLOCK) ON uprod.TIPOINDUMENTARIA2_ID = tipo.ID
				WHERE pip.TIPOTRANSACCION_ID = '{B97FC3BF-902D-4B78-B388-3712988F1DB5}'  
				AND pip.ID = '{E89E1673-4FDB-45F8-AD62-1C5A3CCAA72E}' 
				GROUP BY uitem.PRODUCTO_ID, tipo.NOMBRE, prod.DESCRIPCION
				ORDER BY tipo.NOMBRE, prod.DESCRIPCION