SELECT
    ALIAS_0.ID ALIAS_0_ID,
    ALIAS_0.TIPOOBJETOESTATICO_ID ALIAS_0_TIPOOBJETOESTATICO_ID,
    ALIAS_0.CODIGO ALIAS_0_CODIGO,
    ALIAS_0.ACTIVESTATUS ALIAS_0_ACTIVESTATUS,
    ALIAS_0.DESCRIPCION ALIAS_0_DESCRIPCION,
    ALIAS_1.TALLE ALIAS_1_TALLE,
    ALIAS_2.NOMBRE ALIAS_2_NOMBRE,
    ALIAS_3.DESCRIPCION ALIAS_3_DESCRIPCION,
    ALIAS_4.NOMBRE ALIAS_4_NOMBRE,
    ALIAS_0.STOCKMINIMO ALIAS_0_STOCKMINIMO,
    ALIAS_1.EVALUACION ALIAS_1_EVALUACION,
    ALIAS_8.VALOR2_IMPORTE ALIAS_8_VALOR2_IMPORTE,
    ALIAS_9.NOMBRE ALIAS_9_NOMBRE,
    ALIAS_10.DENOMINACION ALIAS_10_DENOMINACION
FROM
    V_PRODUCTO_ ALIAS_0
    LEFT OUTER JOIN V_UD_PRODUCTO_ ALIAS_5 ON ALIAS_0.BOEXTENSION_ID = ALIAS_5.ID
    LEFT OUTER JOIN V_ITEMTIPOCLASIFICADOR_ ALIAS_2 ON ALIAS_5.TIPOPRODUCTO_ID = ALIAS_2.ID
    LEFT OUTER JOIN V_ITEMTIPOCLASIFICADOR_ ALIAS_4 ON ALIAS_5.TIPOINDUMENTARIA2_ID = ALIAS_4.ID
    LEFT OUTER JOIN V_ITEMESQUEMAOPERATIVO_ ALIAS_6 ON ALIAS_0.ID = ALIAS_6.PLACEOWNER_ID
    INNER JOIN V_UD_PRODUCTO_ ALIAS_1 ON ALIAS_0.BOEXTENSION_ID = ALIAS_1.ID
    LEFT OUTER JOIN V_CUENTASCONTABLES_ ALIAS_7 ON ALIAS_0.CUENTASCONTABLES_ID = ALIAS_7.ID
    LEFT OUTER JOIN V_CUENTA_ ALIAS_3 ON ALIAS_7.CUENTACONTABLE1_ID = ALIAS_3.ID
    INNER JOIN V_PRECIO_ ALIAS_8 ON ALIAS_0.ID = ALIAS_8.REFERENCIA_ID
    INNER JOIN V_LISTAPRECIO_ ALIAS_11 ON ALIAS_8.BO_PLACE_ID = ALIAS_11.PRECIOS_ID
    INNER JOIN V_PROVEEDOR_ ALIAS_10 ON ALIAS_11.ID = ALIAS_10.LISTAPRECIO_ID
    INNER JOIN V_PERSONA_ ALIAS_9 ON ALIAS_10.ENTEASOCIADO_ID = ALIAS_9.ID
    INNER JOIN V_UD_PLAZOENTREGA_ ALIAS_12 ON ALIAS_10.ID = ALIAS_12.PROVEEDOR_ID
    INNER JOIN V_UD_CENTROCOSTOS_ ALIAS_13 ON ALIAS_12.ID = ALIAS_13.PLAZOSENTREGA_ID
    INNER JOIN V_CENTROCOSTOS_ ALIAS_14 ON ALIAS_13.ID = ALIAS_14.BOEXTENSION_ID
WHERE
    ALIAS_0.BO_PLACE_ID = '{DB3AE6D7-8454-4921-8ADD-26804F4158F8}'
    AND ALIAS_0.ACTIVESTATUS = 0
    AND ALIAS_0.TIPOOBJETOESTATICO_ID IS NULL
    AND ALIAS_6.ESQUEMAOPERATIVO_ID IS NULL
    AND ALIAS_10.ACTIVESTATUS = 0
    AND ALIAS_8.DESDEFECHA <= '20240517143959000'
    AND ALIAS_8.HASTAFECHA >= '20240517143959000'
    AND ALIAS_14.ID = '{75A39710-4738-40DB-A208-DF9ABCAC3603}'
ORDER BY
    ALIAS_0.DESCRIPCION