SELECT
	ALIAS_1.NOMBRE ALIAS_1_NOMBRE,
	ALIAS_0.ACTIVESTATUS ALIAS_0_ACTIVESTATUS,
	ALIAS_0.DENOMINACION ALIAS_0_DENOMINACION,
	ALIAS_2.NOMBRE ALIAS_2_NOMBRE,
	ALIAS_3.NUMEROCUENTA ALIAS_3_NUMEROCUENTA,
	ALIAS_4.NOMBRE ALIAS_4_NOMBRE,
	ALIAS_0.CUENTASCONTABLES2_ID ALIAS_0_CUENTASCONTABLES2_ID,
	ALIAS_0.CUENTASCONTABLES3_ID ALIAS_0_CUENTASCONTABLES3_ID,
	ALIAS_0.CUENTASCONTABLES4_ID ALIAS_0_CUENTASCONTABLES4_ID,
	ALIAS_0.CUENTASCONTABLES5_ID ALIAS_0_CUENTASCONTABLES5_ID,
	ALIAS_0.CUENTASCONTABLES6_ID ALIAS_0_CUENTASCONTABLES6_ID,
	ALIAS_0.CUENTASCONTABLES7_ID ALIAS_0_CUENTASCONTABLES7_ID,
	ALIAS_0.CUENTASCONTABLES8_ID ALIAS_0_CUENTASCONTABLES8_ID,
	ALIAS_0.CUENTASCONTABLES9_ID ALIAS_0_CUENTASCONTABLES9_ID,
	ALIAS_0.CUENTASCONTABLES10_ID ALIAS_0_CUENTASCONTABLES10_ID,
	ALIAS_0.CODIGO ALIAS_0_CODIGO,
	ALIAS_5.TIPODOCUMENTO ALIAS_5_TIPODOCUMENTO,
	ALIAS_0.NUMERODOCUMENTO ALIAS_0_NUMERODOCUMENTO,
	ALIAS_0.CUIT ALIAS_0_CUIT,
	ALIAS_6.DESCRIPCION ALIAS_6_DESCRIPCION,
	ALIAS_7.DESCRIPCION ALIAS_7_DESCRIPCION,
	ALIAS_1.CUIT ALIAS_1_CUIT,
	ALIAS_8.NOMBRE ALIAS_8_NOMBRE,
	ALIAS_9.EVALUACION ALIAS_9_EVALUACION,
	ALIAS_9.NC_HABILITADO_N ALIAS_9_NC_HABILITADO_N,
	ALIAS_10.NOMBREDOMICILIO ALIAS_10_NOMBREDOMICILIO,
	ALIAS_11.NUMERO ALIAS_11_NUMERO,
	ALIAS_12.DIRECCIONELECTRONICA ALIAS_12_DIRECCIONELECTRONICA
FROM
	V_PROVEEDOR_ ALIAS_0
	LEFT OUTER JOIN V_PERSONA_ ALIAS_1 ON ALIAS_0.ENTEASOCIADO_ID = ALIAS_1.ID
	LEFT OUTER JOIN V_DOMICILIO_ ALIAS_10 ON ALIAS_1.DOMICILIOPRINCIPAL_ID = ALIAS_10.ID
	LEFT OUTER JOIN V_TELEFONO_ ALIAS_11 ON ALIAS_1.TELEFONOPRINCIPAL_ID = ALIAS_11.ID
	LEFT OUTER JOIN V_DIRECCIONELECTRONICA_ ALIAS_12 ON ALIAS_1.DIRECELECTRONICAPRINCIPAL_ID = ALIAS_12.ID
	LEFT OUTER JOIN V_UNIDADFINANCIERA_ ALIAS_2 ON ALIAS_0.MONEDA_ID = ALIAS_2.ID
	LEFT OUTER JOIN V_ITEMCTABANCARIAPROVEEDOR_ ALIAS_3 ON ALIAS_0.CUENTABANCARIADEFAULT_ID = ALIAS_3.ID
	LEFT OUTER JOIN V_UNIDADFINANCIERA_ ALIAS_4 ON ALIAS_0.MONEDAORIGINAL_ID = ALIAS_4.ID
	LEFT OUTER JOIN V_TIPODOCUMENTO_ ALIAS_5 ON ALIAS_0.TIPODOCUMENTO_ID = ALIAS_5.ID
	LEFT OUTER JOIN V_FLAG_ ALIAS_6 ON ALIAS_0.FLAG_ID = ALIAS_6.ID
	LEFT OUTER JOIN V_ITEMRECURSOUSO_ ALIAS_7 ON ALIAS_0.ITEMRECURSOUSO_ID = ALIAS_7.ID
	LEFT OUTER JOIN V_UD_PROVEEDOR_ ALIAS_9 ON ALIAS_0.BOEXTENSION_ID = ALIAS_9.ID
	LEFT OUTER JOIN V_ITEMTIPOCLASIFICADOR_ ALIAS_8 ON ALIAS_9.TIPOPROVEEDOR_ID = ALIAS_8.ID
WHERE
	ALIAS_0.BO_PLACE_ID = '{39EB5B6C-026B-42AB-A1EA-42F514DB241F}'
	AND ALIAS_0.ACTIVESTATUS = 0
	AND ALIAS_0.TIPOOBJETOESTATICO_ID IS NULL
	AND ALIAS_1.NOMBRE LIKE '%amx%'
ORDER BY
	ALIAS_1.NOMBRE