SELECT
    P.NOMBRE as Nombre,
    cc.NOMBRE AS 'CENTROCOSTOS',
    UCC.ANALISTARRHH_N,
    SUBSTRING (P.FECHANACIMIENTO, 1, 8) AS 'FECHANACIMIENTO',
    DATEDIFF (
        YEAR,
        SUBSTRING (P.FECHANACIMIENTO, 1, 8),
        GETDATE ()
    ) AS 'Cumple'
FROM
    EMPLEADO E
    INNER JOIN PERSONAFISICA P ON E.ENTEASOCIADO_ID = P.ID
    inner join CENTROCOSTOS CC ON CC.ID = E.CENTROCOSTOS_ID
    inner join UD_CENTROCOSTOS UCC ON CC.BOEXTENSION_ID = UCC.ID
WHERE
    e.ACTIVESTATUS = 0
    and MONTH (SUBSTRING (P.FECHANACIMIENTO, 1, 8)) = MONTH (GETDATE ())
    and UCC.ANALISTARRHH_N = 'AVILA LUCAS DAVID'
order by
    3,
    1
select
    dbo.ProperCase (
        SUBSTRING (
            E.DESCRIPCION,
            CHARINDEX ('-', E.DESCRIPCION) + 1,
            LEN (E.DESCRIPCION)
        )
    ) AS 'Empleado',
    CC.nombre AS 'CENTROCOSTOS',
    SUBSTRING (E.FECHAINGRESO, 7, 2) + '/' + SUBSTRING (E.FECHAINGRESO, 5, 2) + '/' + SUBSTRING (E.FECHAINGRESO, 1, 4) AS 'Fecha',
    DATEDIFF (YEAR, e.FECHAINGRESO, GETDATE ()) AS 'Aniversario'
from
    EMPLEADO AS E
    INNER JOIN UD_EMPLEADO UDE ON E.BOEXTENSION_ID = UDE.ID
    inner join CENTROCOSTOS CC ON CC.ID = E.CENTROCOSTOS_ID
    inner join UD_CENTROCOSTOS UCC ON CC.BOEXTENSION_ID = UCC.ID
WHERE
    MONTH (E.FECHAINGRESO) = MONTH (GETDATE ())
    and E.ACTIVESTATUS = 0
    and UCC.ANALISTARRHH_ID = '{4F910D9E-F6E7-4B32-BB81-097F21AE27EB}'
order by
    3,
    2