SELECT
	TOP 50 ALIAS_0.ID ALIAS_0_ID,
	ALIAS_0.COTIZACION ALIAS_0_COTIZACION,
	ALIAS_1.NOMBRE ALIAS_1_NOMBRE,
	Alias_0.Cotizacion * Alias_0.ValorTotal TotalMonedaBase_0,
	(
		select
			CP.SALDO2_IMPORTE
		from
			v_CompromisoPago CP
		where
			CP.TRORIGINANTE_ID = alias_0.id
			and CP.Nivel = 1
	) SALDOCP_0,
FROM
	V_TREGRESOVALORES_ ALIAS_0
	LEFT OUTER JOIN V_MONEDA_ ALIAS_1 ON ALIAS_0.MONEDABASE_ID = ALIAS_1.ID
	LEFT OUTER JOIN V_FLAG_ ALIAS_2 ON ALIAS_0.FLAG_ID = ALIAS_2.ID
	LEFT OUTER JOIN V_UNIDADOPERATIVA_ ALIAS_3 ON ALIAS_0.UNIDADOPERATIVA_ID = ALIAS_3.ID
	LEFT OUTER JOIN V_TIPODISTRIBUCIONCENCOS_ ALIAS_4 ON ALIAS_0.TIPODISTRIBUCIONCENCOS_ID = ALIAS_4.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_5 ON ALIAS_0.DISCRIMINADORCONTABLE4_ID = ALIAS_5.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_6 ON ALIAS_0.DISCRIMINADORCONTABLE5_ID = ALIAS_6.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_7 ON ALIAS_0.DISCRIMINADORCONTABLE6_ID = ALIAS_7.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_8 ON ALIAS_0.DISCRIMINADORCONTABLE7_ID = ALIAS_8.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_9 ON ALIAS_0.DISCRIMINADORCONTABLE8_ID = ALIAS_9.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_10 ON ALIAS_0.DISCRIMINADORCONTABLE9_ID = ALIAS_10.ID
	LEFT OUTER JOIN V_ITEMDISCCONTABLE_ ALIAS_11 ON ALIAS_0.DISCRIMINADORCONTABLE10_ID = ALIAS_11.ID
	LEFT OUTER JOIN V_PUNTOVENTA_ ALIAS_12 ON ALIAS_0.PUNTOVENTA_ID = ALIAS_12.ID
	LEFT OUTER JOIN V_TALONARIO_ ALIAS_13 ON ALIAS_0.TALONARIO_ID = ALIAS_13.ID
	LEFT OUTER JOIN V_AREARESPONSABILIDAD_ ALIAS_14 ON ALIAS_0.AREARESP_ID = ALIAS_14.ID
	LEFT OUTER JOIN V_CPRECIBO_ ALIAS_15 ON ALIAS_0.COMPROMISOPAGO_ID = ALIAS_15.ID
	LEFT OUTER JOIN V_CENTROCOSTOS_ ALIAS_16 ON ALIAS_0.CENTROCOSTOS_ID = ALIAS_16.ID
WHERE
	ALIAS_0.BO_PLACE_ID = '{BD328BAE-89F8-45A9-AD85-FB8F60D28F1A}'
	AND ALIAS_0.TIPOTRANSACCION_ID = '{222C4584-E8BB-45FE-BD71-C3EB0F39F977}'
	AND (
		ALIAS_0.UNIDADOPERATIVA_ID = '{1D28BE85-0586-4EDE-AF3C-FF0FD73FB3A2}'
	)
ORDER BY
	ALIAS_0.FECHAACTUAL DESC,
	ALIAS_0.NUMERODOCUMENTO DESC